/* eslint-disable prettier/prettier */
/* eslint-disable quotes */
const RouteName = {
  SPLSH: 'SplashScreen',
  SWIPER_SCREEN: 'Swiperscreen',
  LOGIN_SCREEN: 'LoginScreen',
  REGISTER_SCREEN: 'Register',
  OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
  HOME_SCREEN: 'HomeScreen',
  TAB_NAVIGATOR: 'TabNavigator',
  REGIATRAION_SUCCESSFULL: 'RegistrationSuccessful',
  HOME_TAB: 'Homesss',
  CHAT_TAB: 'ChatTabsss',
  CALLS_TAB: 'Callszz',
  CHECKOUT_TAB: 'Checkout',
  WALLETS_TAB: 'Wallets',
  PROFILE_TAB: 'Profiless',
  SELECT_LANGUAGE: 'TranslationScreen',
  FORGOT_PASSWORD: 'ForgotPassword',
  CHAT_SCREEN: 'Chatscreen',
  HELP_SCREEN: 'HelpScreen',
  SETTING_SCREEN: 'SettingsScreen',
  FAQ_SCREEN: 'FAQScreen',
  REVIEWS_SCREEN: 'ReviewsScreen',
  NOTIFICTION_SCREEN: 'NotificationScreen',
  PAYMENT_SCREEN: 'PaymentScreen',
  PAYMENT_SUCCESSFULLY: 'PaymentSuccessFully',
  EDIT_PROFILE_SCREEN: 'EditProfileScreen',
  AUDIO_CALL_SCREEN: 'AudioCallScreen',
  LIVE_SCREEN: 'LiveScreen',
  BOOK_A_POOJA_SCREEN: 'BookAPoojaScreen',
  BOOK_POOJA_DETAILES_SCREEN: 'BookPoojaDetailScreen',
  ORDER_HISTORTY_SCREEN: 'OrderHistory',
  ADD_MONEY_TO_WALLET: 'AddMoneyToWallet',
  BUY_MEBERSHIP: 'BuyMembership',
  ASTROMALL_SCREEN: 'AstroMallScreen',
  ASTROMALL_DETAILS_SCREEN: 'AstroMallDetailsScreen',
  ASTROMALL_PANDITLISTING_SCREEN: 'AstroMallPanditListScreen',
  Astrotalks_BLOG_SCREEN: 'AstrotalksBlogScreen',
  Astrotalks_BLOG_DETAILS_SCREEN: 'AstrotalksBlogDetailsScreen',
  DAILY_HOROSCOPE: 'DailyHoroscope',
  FREE_CUNDALI_SCREEN: 'FreeKundliScreen',
  KUNDALI_PROGRESS_SCREEN: 'KundaliProgressScreen',
  KUNDALI_REPORT_SCREEN: 'KundaliReportScreen',
  KUNDALI_MATCHING_SCREEN: 'KundaliMatchingScreen',
  KUNDALI_MATCHING_RESULTS_SCREEN: 'KundaliMatchingResults',
  SEARCH_SCREEN: 'SearchScreen',
  FILTER_SCREEN: 'FilterScreen',
};
export default RouteName;
