import {StyleSheet} from 'react-native';
import {SF, Fonts, SW, SH, widthPercent} from '../../utils';

export default HomeTabStyle = Colors =>
  StyleSheet.create({
    MinViewFirst: {
      width: widthPercent(24),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    MinViewFirstHome: {
      width: widthPercent(24),
    },
    CenteriMAGE: {
      flexDirection: 'row',
      justifyContent: 'center',
    },
    ImageStyle: {
      width: SW(60),
      height: SW(60),
      borderRadius: 200,
    },
    TextColorStyle: {
      color: Colors.black_text_color,
      fontSize: SF(14),
      fontFamily: Fonts.Poppins_Medium,
      textAlign: 'center',
      paddingTop: SH(10),
      opacity: 0.7,
    },
    FlexRowMinView: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
    },
    SearchBortderstyle: {
      borderWidth: SH(1),
      marginHorizontal: SH(20),
      borderRadius: SH(10),
      borderColor: Colors.theme_background,
    },
    SearchBortderstyleHome: {
      borderWidth: SH(1),
      marginHorizontal: SH(20),
      borderRadius: SH(10),
      borderColor: Colors.theme_background,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SH(10),
      paddingVertical: SH(10),
    },
    LootieAnimation: {
      width: SW(90),
      height: SW(90),
    },
    FlexViewLootie: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      borderWidth: 0.5,
      borderColor: Colors.theme_background,
      borderRadius: SH(10),
      paddingVertical: SH(10),
      paddingRight: SH(10),
    },
    AnimationViewWidth: {
      width: '40%',
    },
    TextViewWidth: {
      width: '60%',
    },
    MinTitleStyle: {
      color: Colors.theme_background,
      fontFamily: Fonts.Poppins_Bold,
      fontSize: SF(18),
    },
    SecondTextStyle: {
      color: Colors.gray_text_color,
      fontFamily: Fonts.Poppins_Italic,
      fontSize: SF(16),
    },
    FlexRowLive: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SH(5),
    },
    LiveAstrologyText: {
      color: Colors.theme_background,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(22),
      textAlign: 'left',
    },
    ViewAllTextStyle: {
      color: Colors.black_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(16),
    },
    AstrologersWidth: {
      width: SW(110),
      marginRight: SH(5),
    },
    AstrologerImage: {
      width: SW(90),
      height: SW(110),
      borderRadius: 10,
    },
    PostionTextStyle: {
      color: Colors.black_text_color,
      fontSize: SF(18),
      fontFamily: Fonts.Poppins_Medium,
      textAlign: 'center',
    },
    LinerColorStyle35: {
      position: 'absolute',
      width: SW(120),
      borderRadius: 10,
      height: '35%',
      bottom: 0,
    },
    LinerAround: {
      width: SW(100),
      height: SW(120),
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    LinerAroundBorder: {
      width: SW(120),
      height: SW(120),
      borderRadius: 300,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    LinerAroundChatTab: {
      width: SW(80),
      height: SW(80),
      borderRadius: 300,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    LinerColorStyle35Two: {
      position: 'absolute',
      width: SW(300),
      height: '55%',
      bottom: 0,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
    },
    AstrologyViewNew: {
      position: 'absolute',
      width: '100%',
      height: '55%',
      bottom: 0,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
    },
    ShopMallLiner: {
      position: 'absolute',
      width: SW(230),
      height: '55%',
      bottom: 0,
    },
    AstromallView: {
      position: 'absolute',
      width: widthPercent(46),
      height: '20%',
      bottom: 0,
    },
    PostionShowAbsolute: {
      position: 'absolute',
      top: SH(5),
      zIndex: 23,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      left: SH(13),
      backgroundColor: Colors.red,
      width: SW(30),
      height: SW(30),
      borderRadius: 200,
    },
    BorderWidthView: {
      borderWidth: 1,
      borderColor: Colors.light_gray_text_color,
      borderRadius: 10,
      marginRight: SH(15),
      paddingVertical: SH(20),
      width: SW(140),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    AstrologyView: {
      width: SW(110),
      height: SW(110),
      borderRadius: 200,
    },
    AstrologyViewTextStyle: {
      color: Colors.black_text_color,
      fontSize: SF(18),
      fontFamily: Fonts.Poppins_Medium,
      textAlign: 'center',
      paddingTop: SH(10),
    },
    MinutesTextStyle: {
      color: Colors.gray_text_color,
      fontSize: SF(14),
      fontFamily: Fonts.Poppins_Medium,
      textAlign: 'center',
    },
    ButtonStyle: {
      backgroundColor: Colors.white_text_color,
      borderWidth: 1,
      borderColor: Colors.theme_background,
      borderRadius: 300,
      height: SH(35),
      padding: SH(0),
    },
    ButtonTextStyle: {
      color: Colors.theme_background,
      fontSize: SF(17),
    },
    PostionAbsolute: {
      position: 'absolute',
      top: SH(0),
      left: 0,
      backgroundColor: Colors.theme_background,
      paddingHorizontal: SH(15),
      borderBottomRightRadius: 20,
      borderTopLeftRadius: 20,
    },
    PostionAbsoluteWhite: {
      backgroundColor: Colors.theme_background,
      paddingHorizontal: SH(25),
      paddingVertical: SH(3),
      borderTopRightRadius: 0,
      borderTopLeftRadius: 0,
      borderRadius: 10,
    },
    TextCebnter: {
      color: Colors.white_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(8),
    },
    TextCebnterTheme: {
      color: Colors.white_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(18),
      textAlign: 'center',
    },
    LatestBlogView: {
      width: SW(300),
      marginRight: SH(20),
      borderWidth: 1,
      borderRadius: 10,
      borderColor: Colors.light_gray_text_color,
    },
    AstrotalksBlogView: {
      width: '100%',
      marginRight: SH(20),
      borderWidth: 1,
      borderRadius: 10,
      borderColor: Colors.light_gray_text_color,
      marginBottom: SH(20),
    },
    LatestImageStyle: {
      width: SW(300),
      height: SW(260),
      borderRadius: 10,
    },
    AstrotalksBlogImage: {
      width: '100%',
      height: SW(240),
      borderRadius: 10,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
    },
    LatestTextStyle: {
      color: Colors.white_text_color,
      fontSize: SF(15),
      fontFamily: Fonts.Poppins_Medium,
    },
    AllSidePadding: {
      paddingHorizontal: SH(16),
      position: 'absolute',
      bottom: SH(10),
      width: '100%',
    },
    FlexRowTextStyle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderTopWidth: 0.5,
      borderColor: Colors.light_gray_text_color,
      paddingTop: SH(10),
    },
    SecondTextStyleLetest: {
      color: Colors.white_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(16),
      opacity: 0.8,
    },
    BackgroundMap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.theme_background,
      borderRadius: 200,
      paddingHorizontal: SH(10),
      position: 'absolute',
      right: SH(10),
      top: SH(10),
    },
    LiveTextStyle: {
      color: Colors.white_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(13),
      paddingLeft: SH(5),
      top: SH(1),
    },
    ShopAstromallView: {
      width: SW(230),
      marginRight: SH(20),
    },
    ShopImageView: {
      width: SW(230),
      height: SW(180),
      borderRadius: 10,
    },
    ShpMallImage: {
      width: SW(230),
      height: SW(180),
      borderRadius: 10,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
    },
    SearchTextStyle: {
      color: Colors.gray_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(18),
      paddingLeft: SH(10),
    },
    BottomPostionView: {
      position: 'absolute',
      bottom: SH(0),
      paddingVertical: SH(10),
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SH(10),
      backgroundColor: Colors.white_text_color,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderWidth: 1,
      borderColor: Colors.theme_background,
      borderBottomWidth: 0,
    },
    BackgroundColor: {
      backgroundColor: Colors.theme_background,
      width: '48.5%',
      height: SH(38),
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 300,
      paddingHorizontal: SH(7),
    },
    ChatTewxtStyle: {
      color: Colors.white_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(14),
      paddingLeft: SH(5),
    },
    FlexRowTextWithView: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    TextCentewr: {
      color: Colors.black_text_color,
      fontFamily: Fonts.Poppins_Medium,
      fontSize: SF(16),
      paddingLeft: SH(2),
    },
    CenterView: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    WhiteBgColorMinView: {
      backgroundColor: Colors.white_text_color,
      width: '100%',
      height: '100%',
    },
  });
